### ISSUE TITLE
rendering didn't perform.

### ISSUE THREAD

**Issue by williamfiedler** [torriem/QtAgOpenGPS#1]
Hi.
I had seen your great work.
The code is very nice and I could build it in a short time.
But when running, the rendering didn't perform at all.
So I debug the code and find that the signal ReadyRead() of udpsocket is not emitted at all.

connect(udpSocket,SIGNAL(readyRead()),this,SLOT(udpServerReadDatagrams()));

Please help me for this issue.
Thank you.

**Comment by torriem** [comment]
Back then, there was no simulator, so it did nothing without some UDP NMEA packets to process.  At least as of now the sim works.
