### ISSUE TITLE
What about using QtQuick3D to draw 3D tractor?

### ISSUE THREAD

**Issue by munhktamir** [torriem/QtAgOpenGPS#18]
I tried some Qt stuff a few months ago. Qt5.15 can render 3D objects easily.
![image](https://github.com/torriem/QtAgOpenGPS/assets/11732020/a0768053-a517-4191-ac8a-85ba577090f3)

**Comment by torriem** [comment]
Could be done eventually, but not without significant re-writing of the backend.  and we don't even have a functioning version yet.  So some day but won't be anytime soon.
