### ISSUE TITLE
EGLFS: OpenGL Windows cannot be mixed with others

### ISSUE THREAD

**Issue by munhktamir** [torriem/QtAgOpenGPS#3]
Hello, Dear Torriem. How are you? I was really busy to graduate my master course.
Now, I am available to develop QtAgOpenGPS. A few days, I spent time to prepare my hardware. Today, I successfully modified Qt5.9.8 to i.MX6Q microprocessor. I have compiled application but I occurred some problem when i execute. see the picture.
![59484619-7b433800-8ead-11e9-87df-75b6b42da954](https://user-images.githubusercontent.com/11732020/59552211-f8120700-8fbe-11e9-9ada-439811beec26.png)

How can i solve this? did you faced with this error ?

**Comment by torriem** [comment]
On 06/15/2019 07:43 AM, Munkhtamir wrote:
> Hello, Dear Torriem. How are you? I was really busy to graduate my master course.
> Now, I am available to develop QtAgOpenGPS. A few days, I spent time to prepare my hardware. Today, I successfully modified Qt5.9.8 to i.MX6Q microprocessor. I have compiled application but I occurred some problem when i execute. see the picture.
> ![59484619-7b433800-8ead-11e9-87df-75b6b42da954](https://user-images.githubusercontent.com/11732020/59552211-f8120700-8fbe-11e9-9ada-439811beec26.png)
> 
> How can i solve this? did you faced with this error ?

This error means that your embedded hardware only supports OpenGL ES.
There still are some old-style, immediate-mode OpenGL calls in QtOAG
that need to be converted to OpenGL ES to use buffers and vectors. This
isn't terribly hard, and needs to be done.  The goal is to have QtAOG
OpenGL ES only so it will run on the older hardware.

Also I don't think you can remotely run OpenGL graphics via Putty.

**Comment by munhktamir** [comment]
Freescale's microprocessors have been supporting several display drivers. You know, for example; wayland, eglfs, x11 with egl(xcb). At this time, i prepared EGLFS for run the applications. But, as for QtAOG, it is not enough right? Could you give me some hint to modify or change in the QtAOG source ?
Should I change my hardware or display driver ?
Thank you,

**Comment by torriem** [comment]
On 06/27/2019 09:26 AM, Munkhtamir wrote:
> Freescale's microprocessors have been supporting several display drivers. You know, for example; wayland, eglfs, x11 with egl(xcb). At this time, i prepared EGLFS for run the applications. But, as for QtAOG, it is not enough right? Could you give me some hint to modify or change in the QtAOG source ?
> Should I change my hardware or display driver ?

I don't think you need to change your hardware or display driver.  And
I'm not totally sure where in QtAOG the OpenGL 2.1 code is still there.

The only suggestion I have is to read up on OpenGL immediate code and
then read up on OpenGL ES and shaders.  Maybe some OpenGL tutorials.  Qt
provides its own wrappers to OpenGL calls, which you can see in my code.
But they are the same calls and have the same names.  The only special
things I use are Qt classes for defining matrices and doing translations
and rotations.

I hope in the future to be able to work on QtAOG again, but for the next
6 months or so that's just not going to be possible.

**Comment by torriem** [comment]
Even in its incomplete state, I don't think there's any old-style OpenGL code anymore. It's all OpenGL ES now

**Comment by munhktamir** [comment]
Hello Michael, long time no see. I am still working on it. I made a lot of code on the QML side. But still considering improving code design since Brian made changes a lot.

**Comment by torriem** [comment]
hi there.  Sounds great. Look forward to seeing it at some point.  Yes AOG is moving rapidly which makes it really hard to keep up.  Kind of like Wine on Linux!

Been a busy winter, building a new building and helping to build a house.  Now spring is here and we're getting ready to plant.  Still dreaming of working on QtAOG again some time!

**Comment by munhktamir** [comment]
I too happy to work with you on QtAOG. Everything works good but there is some problem related to displaying the line number next to vehicle. Like overdrawing or overlapping. I thought it might be cannot clear the buffer. Do you have an idea for it?

**Comment by sonicpp** [comment]
Hello guys,
I know this is not perfect place for communicating such a things, but I see you are here cooperating some work on QtAOG.I previously implemented reading GPS data from uart (thanks @torriem for merging), and next big thing I need to do (I already used QtAOG in the field!) is AB curve. Is anyone working on this or should I give it a try? @munhktamir may I ask you what are you working on now?

Thanks!

**Comment by munhktamir** [comment]
Hello,
I have converted QtAOG into a C version that can be run on ECU or Linux environment but not tried the HAL part. Also, made several GUI using QML, and CAN communication including message queue. At this moment, I needed just AB straight-line guidance. But the next plan would be AB curve for sure.
