### ISSUE TITLE
If headland exists but boundary is deleted, crashes when loading field

### ISSUE THREAD

**Issue by torriem** [torriem/QtAgOpenGPS#31]
If you delete all the boundaries, but the headland still exists, when headland.txt is loaded we get a crash.  AOG does not crash, but displays message that headland is corrupt.  Check AOG's handling of this situation, fix QtAOG to not crash.

**Comment by Davidwedel** [comment]
If you delete the boundary, delete the headland, right?

**Comment by torriem** [comment]
Yes I think that's a good idea.  I still need to prevent the crash, though, in case you open a field from AOG where the boundary is gone but the headland exists.
