### ISSUE TITLE
Add the feature page, and fancy line editor

### ISSUE THREAD

**Issue by Davidwedel** [torriem/QtAgOpenGPS#32]

**Comment by Henny20** [comment]
A quick translation of AgIO to Avalonia: https://github.com/Henny20/AAgIO.

**Comment by torriem** [comment]
That's awesome!  Do you want to Join us in a telegram group discussing AOG development and also alternative ports (such as the Qt/C++ one)? Brian Tischler is there, and also a few other contributors including some people with C# experience who have long thought about using Avalonia.  

Also if you could tell me how to build and run AAgIO on Fedora I'd be grateful.

**Comment by Davidwedel** [comment]
> _No description provided._
this is done now in uiDev
