### ISSUE TITLE
Bug in SpinBoxCustomized

### ISSUE THREAD

**Issue by Davidwedel** [torriem/QtAgOpenGPS#43]
Here I am again :). 
SpinBoxCustomized has a bug where we can only adjust the value with the arrow keys. Trying to adjust the value by the system keyboard doesn't work. The value is shown, but is never "written" to the true value.

All of the spinboxes are a real mess. Like any of the components that have several variants. Really, they need to be consolidated into something more concise, instead of 7 different options. 

I'll put a list here of their separate functions, to try to make sense of the mess:

SpinBoxFusion: A copy of the default SpinBox, but the default SpinBox component has a [binding loop](https://bugreports.qt.io/browse/QTBUG-118545) in it, which I think is fixed in it. That is all that is changed, I think, except for a few colors, which follow AOGTheme.

SpinBoxDouble: Derived from 	MLDoubleSpinBox (https://github.com/mpaperno/maxLibQt), which "is a drop-in replacement for QtQuick Controls 2 SpinBox which can handle double-precision numbers and long integers.", but I fixed the errors caused by Qt6.  I think that all the spinboxes should be based on this, instead of SpinBoxFusion.

SpinBoxCustomized: This is based off of SpinBoxFusion, and has some error handling for min/max values. Cannot take decimals, but has some decimal handling for some of its children.

SpinBoxOneDecimal: This has an Item{} as root (why?) but is based off the default SpinBox{}, and can handle, believe it or not, one decimal.

SpinBoxDecimal: Based off of SpinBoxCustomized, but can have as many decimals as we want. Really, this and the OneDecimal variant should be merged.

SpinBoxCM: Based off Customized, to, from, and the displayed value are all in cm, but the "real value" is always meters.

SpinBoxKM: Ditto the last, but to, from, and displayed are KM

SpinBoxM: Based off of SpinBoxDouble, so can handle decimals.

The last 3 here all can correctly display imperial values, while the "real" value is always in M.

Plan: I think that SpinBoxDouble needs to be the main, with Fusion deleted. Then, Decimal, and OneDecimal can be deleted. Then Customized can do the min/max checking(or should this go in Double, and be activated with a bool?). M, CM, and KM probably have to remain their own, as they require different correction for imperial/metric. But they can at least be based on Customized, instead of all different.

What makes this all more tricky, is that the components directory is copied over to the AgIO side, for its QML files. I don't know of any easy way to have them both reference the same directory.

**Comment by torriem** [comment]
I agree.

**Comment by Davidwedel** [comment]
OK. That was a stupid mistake. I hadn't set "editable: true" on the spinboxes, so of course I couldn't edit them with the keyboard. The "bug" was a programmer error.

At least it forced me to clean up the spinboxes a little.
